// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoundBeats.Infrastructure.Data;

namespace SoundBeats.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SoundBeatsDbContext))]
    partial class SoundBeatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SoundBeats.Core.Domain.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .HasColumnType("text");

                    b.Property<byte[]>("PhotoCover")
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .IsUnique();

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ISO2")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("ISO3")
                        .HasColumnType("varchar(3)")
                        .HasMaxLength(3);

                    b.Property<string>("NameEn")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("NameEs")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISO2 = "AD",
                            ISO3 = "AND",
                            NameEn = " ",
                            NameEs = "Andorra"
                        },
                        new
                        {
                            Id = 2,
                            ISO2 = "AE",
                            ISO3 = "ARE",
                            NameEn = " ",
                            NameEs = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 3,
                            ISO2 = "AF",
                            ISO3 = "AFG",
                            NameEn = " ",
                            NameEs = "Afganistán"
                        },
                        new
                        {
                            Id = 4,
                            ISO2 = "AG",
                            ISO3 = "ATG",
                            NameEn = " ",
                            NameEs = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = 5,
                            ISO2 = "AI",
                            ISO3 = "AIA",
                            NameEn = " ",
                            NameEs = "Anguila"
                        },
                        new
                        {
                            Id = 6,
                            ISO2 = "AL",
                            ISO3 = "ALB",
                            NameEn = " ",
                            NameEs = "Albania"
                        },
                        new
                        {
                            Id = 7,
                            ISO2 = "AL",
                            ISO3 = "ALB",
                            NameEn = " ",
                            NameEs = "Albania"
                        },
                        new
                        {
                            Id = 8,
                            ISO2 = "AM",
                            ISO3 = "ARM",
                            NameEn = " ",
                            NameEs = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            ISO2 = "AN",
                            ISO3 = "ANT",
                            NameEn = " ",
                            NameEs = "Antillas Holandesas"
                        },
                        new
                        {
                            Id = 10,
                            ISO2 = "AO",
                            ISO3 = "AGO",
                            NameEn = " ",
                            NameEs = "Angola"
                        },
                        new
                        {
                            Id = 11,
                            ISO2 = "AQ",
                            ISO3 = "ATA",
                            NameEn = " ",
                            NameEs = "Antártida"
                        },
                        new
                        {
                            Id = 12,
                            ISO2 = "AR",
                            ISO3 = "ARG",
                            NameEn = " ",
                            NameEs = "Argentina"
                        },
                        new
                        {
                            Id = 13,
                            ISO2 = "AS",
                            ISO3 = "ASM",
                            NameEn = " ",
                            NameEs = "Samoa Americana"
                        },
                        new
                        {
                            Id = 14,
                            ISO2 = "AT",
                            ISO3 = "AUT",
                            NameEn = " ",
                            NameEs = "Austria"
                        },
                        new
                        {
                            Id = 15,
                            ISO2 = "AU",
                            ISO3 = "AUS",
                            NameEn = " ",
                            NameEs = "Australia"
                        },
                        new
                        {
                            Id = 16,
                            ISO2 = "AW",
                            ISO3 = "ABW",
                            NameEn = " ",
                            NameEs = "Aruba"
                        },
                        new
                        {
                            Id = 17,
                            ISO2 = "AX",
                            ISO3 = "ALA",
                            NameEn = " ",
                            NameEs = "Islas Aland"
                        },
                        new
                        {
                            Id = 18,
                            ISO2 = "AZ",
                            ISO3 = "AZE",
                            NameEn = " ",
                            NameEs = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 19,
                            ISO2 = "BA",
                            ISO3 = "BIH",
                            NameEn = " ",
                            NameEs = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 20,
                            ISO2 = "BB",
                            ISO3 = "BRB",
                            NameEn = " ",
                            NameEs = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            ISO2 = "BD",
                            ISO3 = "BGD",
                            NameEn = " ",
                            NameEs = "Bangladesh"
                        },
                        new
                        {
                            Id = 22,
                            ISO2 = "BE",
                            ISO3 = "BEL",
                            NameEn = " ",
                            NameEs = "Bélgica"
                        },
                        new
                        {
                            Id = 23,
                            ISO2 = "BF",
                            ISO3 = "BFA",
                            NameEn = " ",
                            NameEs = "Burkina Faso"
                        },
                        new
                        {
                            Id = 24,
                            ISO2 = "BG",
                            ISO3 = "BGR",
                            NameEn = " ",
                            NameEs = "Bulgaria"
                        },
                        new
                        {
                            Id = 25,
                            ISO2 = "BH",
                            ISO3 = "BHR",
                            NameEn = " ",
                            NameEs = "Bahrein"
                        },
                        new
                        {
                            Id = 26,
                            ISO2 = "BI",
                            ISO3 = "BDI",
                            NameEn = " ",
                            NameEs = "Burundi"
                        },
                        new
                        {
                            Id = 27,
                            ISO2 = "BJ",
                            ISO3 = "BEN",
                            NameEn = " ",
                            NameEs = "Benín"
                        },
                        new
                        {
                            Id = 28,
                            ISO2 = "BM",
                            ISO3 = "BMU",
                            NameEn = " ",
                            NameEs = "Bermudas"
                        },
                        new
                        {
                            Id = 29,
                            ISO2 = "BN",
                            ISO3 = "BRN",
                            NameEn = " ",
                            NameEs = "Brunei"
                        },
                        new
                        {
                            Id = 30,
                            ISO2 = "BO",
                            ISO3 = "BOL",
                            NameEn = " ",
                            NameEs = "Bolivia"
                        },
                        new
                        {
                            Id = 31,
                            ISO2 = "BR",
                            ISO3 = "BRA",
                            NameEn = " ",
                            NameEs = "Brasil"
                        },
                        new
                        {
                            Id = 32,
                            ISO2 = "BS",
                            ISO3 = "BHS",
                            NameEn = " ",
                            NameEs = "Bahamas"
                        },
                        new
                        {
                            Id = 33,
                            ISO2 = "BT",
                            ISO3 = "BTN",
                            NameEn = " ",
                            NameEs = "Bután"
                        },
                        new
                        {
                            Id = 34,
                            ISO2 = "BV",
                            ISO3 = "BVT",
                            NameEn = " ",
                            NameEs = "Isla Bouvet"
                        },
                        new
                        {
                            Id = 35,
                            ISO2 = "BW",
                            ISO3 = "BWA",
                            NameEn = " ",
                            NameEs = "Botswana"
                        },
                        new
                        {
                            Id = 36,
                            ISO2 = "BY",
                            ISO3 = "BLR",
                            NameEn = " ",
                            NameEs = "Bielorusia"
                        },
                        new
                        {
                            Id = 37,
                            ISO2 = "BZ",
                            ISO3 = "BLZ",
                            NameEn = " ",
                            NameEs = "Belice"
                        },
                        new
                        {
                            Id = 38,
                            ISO2 = "CA",
                            ISO3 = "CAN",
                            NameEn = " ",
                            NameEs = "Canadá"
                        },
                        new
                        {
                            Id = 39,
                            ISO2 = "CC",
                            ISO3 = "CCK",
                            NameEn = " ",
                            NameEs = "Islas Cocos"
                        },
                        new
                        {
                            Id = 40,
                            ISO2 = "CD",
                            ISO3 = "COD",
                            NameEn = " ",
                            NameEs = "Republica Democrática del Congo"
                        },
                        new
                        {
                            Id = 41,
                            ISO2 = "CF",
                            ISO3 = "CAF",
                            NameEn = " ",
                            NameEs = "República Centrofricana"
                        },
                        new
                        {
                            Id = 42,
                            ISO2 = "CG",
                            ISO3 = "COG",
                            NameEn = " ",
                            NameEs = "República del Congo"
                        },
                        new
                        {
                            Id = 43,
                            ISO2 = "CH",
                            ISO3 = "CHE",
                            NameEn = " ",
                            NameEs = "Suiza"
                        },
                        new
                        {
                            Id = 44,
                            ISO2 = "CI",
                            ISO3 = "CIV",
                            NameEn = " ",
                            NameEs = "Costa de Marfil"
                        },
                        new
                        {
                            Id = 45,
                            ISO2 = "CK",
                            ISO3 = "COK",
                            NameEn = " ",
                            NameEs = "Islas Cook"
                        },
                        new
                        {
                            Id = 46,
                            ISO2 = "CL",
                            ISO3 = "CHL",
                            NameEn = " ",
                            NameEs = "Chile"
                        },
                        new
                        {
                            Id = 47,
                            ISO2 = "CM",
                            ISO3 = "CMR",
                            NameEn = " ",
                            NameEs = "Camerún"
                        },
                        new
                        {
                            Id = 48,
                            ISO2 = "CN",
                            ISO3 = "CHN",
                            NameEn = " ",
                            NameEs = "China"
                        },
                        new
                        {
                            Id = 49,
                            ISO2 = "CO",
                            ISO3 = "COL",
                            NameEn = " ",
                            NameEs = "Colombia"
                        },
                        new
                        {
                            Id = 50,
                            ISO2 = "CR",
                            ISO3 = "CRI",
                            NameEn = " ",
                            NameEs = "Costa Rica"
                        },
                        new
                        {
                            Id = 51,
                            ISO2 = "CU",
                            ISO3 = "CUB",
                            NameEn = " ",
                            NameEs = "Cuba"
                        },
                        new
                        {
                            Id = 52,
                            ISO2 = "CV",
                            ISO3 = "CPV",
                            NameEn = " ",
                            NameEs = "Cabo Verde"
                        },
                        new
                        {
                            Id = 53,
                            ISO2 = "CX",
                            ISO3 = "CXR",
                            NameEn = " ",
                            NameEs = "Isla de Navidad"
                        },
                        new
                        {
                            Id = 54,
                            ISO2 = "CY",
                            ISO3 = "CYP",
                            NameEn = " ",
                            NameEs = "Chipre"
                        },
                        new
                        {
                            Id = 55,
                            ISO2 = "CZ",
                            ISO3 = "CZE",
                            NameEn = " ",
                            NameEs = "República Checa"
                        },
                        new
                        {
                            Id = 56,
                            ISO2 = "DE",
                            ISO3 = "DEU",
                            NameEn = " ",
                            NameEs = "Alemania"
                        },
                        new
                        {
                            Id = 57,
                            ISO2 = "DJ",
                            ISO3 = "DJI",
                            NameEn = " ",
                            NameEs = "Yibuti"
                        },
                        new
                        {
                            Id = 58,
                            ISO2 = "DK",
                            ISO3 = "DNK",
                            NameEn = " ",
                            NameEs = "Dinamarca"
                        },
                        new
                        {
                            Id = 59,
                            ISO2 = "DM",
                            ISO3 = "DMA",
                            NameEn = " ",
                            NameEs = "Dominica"
                        },
                        new
                        {
                            Id = 60,
                            ISO2 = "DO",
                            ISO3 = "DOM",
                            NameEn = " ",
                            NameEs = "República Dominicana"
                        },
                        new
                        {
                            Id = 61,
                            ISO2 = "DZ",
                            ISO3 = "DZA",
                            NameEn = " ",
                            NameEs = "Argelia"
                        },
                        new
                        {
                            Id = 62,
                            ISO2 = "EC",
                            ISO3 = "ECU",
                            NameEn = " ",
                            NameEs = "Ecuador"
                        },
                        new
                        {
                            Id = 63,
                            ISO2 = "EE",
                            ISO3 = "EST",
                            NameEn = " ",
                            NameEs = "Estonia"
                        },
                        new
                        {
                            Id = 64,
                            ISO2 = "EG",
                            ISO3 = "EGY",
                            NameEn = " ",
                            NameEs = "Egipto"
                        },
                        new
                        {
                            Id = 65,
                            ISO2 = "EH",
                            ISO3 = "ESH",
                            NameEn = " ",
                            NameEs = "Sahara Occidental"
                        },
                        new
                        {
                            Id = 66,
                            ISO2 = "ER",
                            ISO3 = "ERI",
                            NameEn = " ",
                            NameEs = "Eritrea"
                        },
                        new
                        {
                            Id = 67,
                            ISO2 = "ES",
                            ISO3 = "ESP",
                            NameEn = " ",
                            NameEs = "España"
                        },
                        new
                        {
                            Id = 68,
                            ISO2 = "ET",
                            ISO3 = "ETH",
                            NameEn = " ",
                            NameEs = "Etiopía"
                        },
                        new
                        {
                            Id = 69,
                            ISO2 = "FI",
                            ISO3 = "FIN",
                            NameEn = " ",
                            NameEs = "Finlandia"
                        },
                        new
                        {
                            Id = 70,
                            ISO2 = "FJ",
                            ISO3 = "FJI",
                            NameEn = " ",
                            NameEs = "Fiji"
                        },
                        new
                        {
                            Id = 71,
                            ISO2 = "FK",
                            ISO3 = "FLK",
                            NameEn = " ",
                            NameEs = "Islas Malvinas"
                        },
                        new
                        {
                            Id = 72,
                            ISO2 = "FM",
                            ISO3 = "FSM",
                            NameEn = " ",
                            NameEs = "Micronesia"
                        },
                        new
                        {
                            Id = 73,
                            ISO2 = "FO",
                            ISO3 = "FRO",
                            NameEn = " ",
                            NameEs = "Islas Faroe"
                        },
                        new
                        {
                            Id = 74,
                            ISO2 = "FR",
                            ISO3 = "FRA",
                            NameEn = " ",
                            NameEs = "Francia"
                        },
                        new
                        {
                            Id = 75,
                            ISO2 = "GA",
                            ISO3 = "GAB",
                            NameEn = " ",
                            NameEs = "Gabón"
                        },
                        new
                        {
                            Id = 76,
                            ISO2 = "GB",
                            ISO3 = "GBR",
                            NameEn = " ",
                            NameEs = "Reino Unido"
                        },
                        new
                        {
                            Id = 77,
                            ISO2 = "GD",
                            ISO3 = "GRD",
                            NameEn = " ",
                            NameEs = "Granada"
                        },
                        new
                        {
                            Id = 78,
                            ISO2 = "GE",
                            ISO3 = "GEO",
                            NameEn = " ",
                            NameEs = "Georgia"
                        },
                        new
                        {
                            Id = 79,
                            ISO2 = "GF",
                            ISO3 = "GUF",
                            NameEn = " ",
                            NameEs = "Guayana Francesa"
                        },
                        new
                        {
                            Id = 80,
                            ISO2 = "GG",
                            ISO3 = "GGY",
                            NameEn = " ",
                            NameEs = "Guernsey"
                        },
                        new
                        {
                            Id = 81,
                            ISO2 = "GH",
                            ISO3 = "GHA",
                            NameEn = " ",
                            NameEs = "Ghana"
                        },
                        new
                        {
                            Id = 82,
                            ISO2 = "GI",
                            ISO3 = "GIB",
                            NameEn = " ",
                            NameEs = "Gibraltar"
                        },
                        new
                        {
                            Id = 83,
                            ISO2 = "GL",
                            ISO3 = "GRL",
                            NameEn = " ",
                            NameEs = "Groenlandia"
                        },
                        new
                        {
                            Id = 84,
                            ISO2 = "GM",
                            ISO3 = "GMB",
                            NameEn = " ",
                            NameEs = "Gambia"
                        },
                        new
                        {
                            Id = 85,
                            ISO2 = "GN",
                            ISO3 = "GIN",
                            NameEn = " ",
                            NameEs = "Guinea"
                        },
                        new
                        {
                            Id = 86,
                            ISO2 = "GP",
                            ISO3 = "GLP",
                            NameEn = " ",
                            NameEs = "Guadalupe"
                        },
                        new
                        {
                            Id = 87,
                            ISO2 = "GQ",
                            ISO3 = "GNQ",
                            NameEn = " ",
                            NameEs = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = 88,
                            ISO2 = "GR",
                            ISO3 = "GRC",
                            NameEn = " ",
                            NameEs = "Grecia"
                        },
                        new
                        {
                            Id = 89,
                            ISO2 = "GS",
                            ISO3 = "SGS",
                            NameEn = " ",
                            NameEs = "Georgia del Sur y las islas Sandwich"
                        },
                        new
                        {
                            Id = 90,
                            ISO2 = "GT",
                            ISO3 = "GTM",
                            NameEn = " ",
                            NameEs = "Guatemala"
                        },
                        new
                        {
                            Id = 91,
                            ISO2 = "GU",
                            ISO3 = "GUM",
                            NameEn = " ",
                            NameEs = "Guam"
                        },
                        new
                        {
                            Id = 92,
                            ISO2 = "GW",
                            ISO3 = "GNB",
                            NameEn = " ",
                            NameEs = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 93,
                            ISO2 = "GY",
                            ISO3 = "GUY",
                            NameEn = " ",
                            NameEs = "Guyana"
                        },
                        new
                        {
                            Id = 94,
                            ISO2 = "HK",
                            ISO3 = "HKG",
                            NameEn = " ",
                            NameEs = "Hong Kong"
                        },
                        new
                        {
                            Id = 95,
                            ISO2 = "HM",
                            ISO3 = "HMD",
                            NameEn = " ",
                            NameEs = "Islas Heard y McDonald"
                        },
                        new
                        {
                            Id = 96,
                            ISO2 = "HN",
                            ISO3 = "HND",
                            NameEn = " ",
                            NameEs = "Honduras"
                        },
                        new
                        {
                            Id = 97,
                            ISO2 = "HR",
                            ISO3 = "HRV",
                            NameEn = " ",
                            NameEs = "Croacia"
                        },
                        new
                        {
                            Id = 98,
                            ISO2 = "HT",
                            ISO3 = "HTI",
                            NameEn = " ",
                            NameEs = "Haití"
                        },
                        new
                        {
                            Id = 99,
                            ISO2 = "HU",
                            ISO3 = "HUN",
                            NameEn = " ",
                            NameEs = "Hungría"
                        },
                        new
                        {
                            Id = 100,
                            ISO2 = "ID",
                            ISO3 = "IDN",
                            NameEn = " ",
                            NameEs = "Indonesia"
                        },
                        new
                        {
                            Id = 101,
                            ISO2 = "IE",
                            ISO3 = "IRL",
                            NameEn = " ",
                            NameEs = "Irlanda"
                        },
                        new
                        {
                            Id = 102,
                            ISO2 = "IL",
                            ISO3 = "ISR",
                            NameEn = " ",
                            NameEs = "Israel"
                        },
                        new
                        {
                            Id = 103,
                            ISO2 = "IM",
                            ISO3 = "IMN",
                            NameEn = " ",
                            NameEs = "Isla de Man"
                        },
                        new
                        {
                            Id = 104,
                            ISO2 = "IN",
                            ISO3 = "IND",
                            NameEn = " ",
                            NameEs = "India"
                        },
                        new
                        {
                            Id = 105,
                            ISO2 = "IO",
                            ISO3 = "IOT",
                            NameEn = " ",
                            NameEs = "Terrirorio Británico del Océano Índico"
                        },
                        new
                        {
                            Id = 106,
                            ISO2 = "IQ",
                            ISO3 = "IRQ",
                            NameEn = " ",
                            NameEs = "Irak"
                        },
                        new
                        {
                            Id = 107,
                            ISO2 = "IR",
                            ISO3 = "IRN",
                            NameEn = " ",
                            NameEs = "Irán"
                        },
                        new
                        {
                            Id = 108,
                            ISO2 = "IS",
                            ISO3 = "ISL",
                            NameEn = " ",
                            NameEs = "Islandia"
                        },
                        new
                        {
                            Id = 109,
                            ISO2 = "IT",
                            ISO3 = "ITA",
                            NameEn = " ",
                            NameEs = "Italia"
                        },
                        new
                        {
                            Id = 110,
                            ISO2 = "JE",
                            ISO3 = "JEY",
                            NameEn = " ",
                            NameEs = "Jersey"
                        },
                        new
                        {
                            Id = 111,
                            ISO2 = "JM",
                            ISO3 = "JAM",
                            NameEn = " ",
                            NameEs = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            ISO2 = "JO",
                            ISO3 = "JOR",
                            NameEn = " ",
                            NameEs = "Jordania"
                        },
                        new
                        {
                            Id = 113,
                            ISO2 = "JP",
                            ISO3 = "JPN",
                            NameEn = " ",
                            NameEs = "Japón"
                        },
                        new
                        {
                            Id = 114,
                            ISO2 = "KE",
                            ISO3 = "KEN",
                            NameEn = " ",
                            NameEs = "Kenia"
                        },
                        new
                        {
                            Id = 115,
                            ISO2 = "KG",
                            ISO3 = "KGZ",
                            NameEn = " ",
                            NameEs = "Kirguistán"
                        },
                        new
                        {
                            Id = 116,
                            ISO2 = "KH",
                            ISO3 = "KHM",
                            NameEn = " ",
                            NameEs = "Camboya"
                        },
                        new
                        {
                            Id = 117,
                            ISO2 = "KI",
                            ISO3 = "KIR",
                            NameEn = " ",
                            NameEs = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            ISO2 = "KM",
                            ISO3 = "COM",
                            NameEn = " ",
                            NameEs = "Comoras"
                        },
                        new
                        {
                            Id = 119,
                            ISO2 = "KN",
                            ISO3 = "KNA",
                            NameEn = " ",
                            NameEs = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = 120,
                            ISO2 = "KP",
                            ISO3 = "PRK",
                            NameEn = " ",
                            NameEs = "República Democrática de Corea"
                        },
                        new
                        {
                            Id = 121,
                            ISO2 = "KR",
                            ISO3 = "KOR",
                            NameEn = " ",
                            NameEs = "República de Corea"
                        },
                        new
                        {
                            Id = 122,
                            ISO2 = "KW",
                            ISO3 = "KWT",
                            NameEn = " ",
                            NameEs = "Kuwait"
                        },
                        new
                        {
                            Id = 123,
                            ISO2 = "KY",
                            ISO3 = "CYM",
                            NameEn = " ",
                            NameEs = "Islas Caimán"
                        },
                        new
                        {
                            Id = 124,
                            ISO2 = "KZ",
                            ISO3 = "KAZ",
                            NameEn = " ",
                            NameEs = "Kasajistán"
                        },
                        new
                        {
                            Id = 125,
                            ISO2 = "LA",
                            ISO3 = "LAO",
                            NameEn = " ",
                            NameEs = "Laos"
                        },
                        new
                        {
                            Id = 126,
                            ISO2 = "LB",
                            ISO3 = "LBN",
                            NameEn = " ",
                            NameEs = "Líbano"
                        },
                        new
                        {
                            Id = 127,
                            ISO2 = "LC",
                            ISO3 = "LCA",
                            NameEn = " ",
                            NameEs = "Santa Lucía"
                        },
                        new
                        {
                            Id = 128,
                            ISO2 = "LI",
                            ISO3 = "LIE",
                            NameEn = " ",
                            NameEs = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            ISO2 = "LK",
                            ISO3 = "LKA",
                            NameEn = " ",
                            NameEs = "Sri Lanka"
                        },
                        new
                        {
                            Id = 130,
                            ISO2 = "LR",
                            ISO3 = "LBR",
                            NameEn = " ",
                            NameEs = "Liberia"
                        },
                        new
                        {
                            Id = 131,
                            ISO2 = "LS",
                            ISO3 = "LSO",
                            NameEn = " ",
                            NameEs = "Lesotho"
                        },
                        new
                        {
                            Id = 132,
                            ISO2 = "LT",
                            ISO3 = "LTU",
                            NameEn = " ",
                            NameEs = "Lituana"
                        },
                        new
                        {
                            Id = 133,
                            ISO2 = "LU",
                            ISO3 = "LUX",
                            NameEn = " ",
                            NameEs = "Luxembur "
                        },
                        new
                        {
                            Id = 134,
                            ISO2 = "LV",
                            ISO3 = "LVA",
                            NameEn = " ",
                            NameEs = "Letonia"
                        },
                        new
                        {
                            Id = 135,
                            ISO2 = "LY",
                            ISO3 = "LBY",
                            NameEn = " ",
                            NameEs = "Libia"
                        },
                        new
                        {
                            Id = 136,
                            ISO2 = "MA",
                            ISO3 = "MAR",
                            NameEn = " ",
                            NameEs = "Marruecos"
                        },
                        new
                        {
                            Id = 137,
                            ISO2 = "MC",
                            ISO3 = "MCO",
                            NameEn = " ",
                            NameEs = "Mónaco"
                        },
                        new
                        {
                            Id = 138,
                            ISO2 = "MD",
                            ISO3 = "MDA",
                            NameEn = " ",
                            NameEs = "Moldavia"
                        },
                        new
                        {
                            Id = 139,
                            ISO2 = "ME",
                            ISO3 = "MNE",
                            NameEn = " ",
                            NameEs = "Montenegro"
                        },
                        new
                        {
                            Id = 140,
                            ISO2 = "MG",
                            ISO3 = "MDG",
                            NameEn = " ",
                            NameEs = "Madagascar"
                        },
                        new
                        {
                            Id = 141,
                            ISO2 = "MH",
                            ISO3 = "MHL",
                            NameEn = " ",
                            NameEs = "Islas Marschall"
                        },
                        new
                        {
                            Id = 142,
                            ISO2 = "MK",
                            ISO3 = "MKD",
                            NameEn = " ",
                            NameEs = "Macedonia"
                        },
                        new
                        {
                            Id = 143,
                            ISO2 = "ML",
                            ISO3 = "MLI",
                            NameEn = " ",
                            NameEs = "Malí"
                        },
                        new
                        {
                            Id = 144,
                            ISO2 = "MM",
                            ISO3 = "MMR",
                            NameEn = " ",
                            NameEs = "Myanmar"
                        },
                        new
                        {
                            Id = 145,
                            ISO2 = "MN",
                            ISO3 = "MNG",
                            NameEn = " ",
                            NameEs = "Mon lia"
                        },
                        new
                        {
                            Id = 146,
                            ISO2 = "MO",
                            ISO3 = "MAC",
                            NameEn = " ",
                            NameEs = "Macao"
                        },
                        new
                        {
                            Id = 147,
                            ISO2 = "MP",
                            ISO3 = "MNP",
                            NameEn = " ",
                            NameEs = "Islas Marianas del Norte"
                        },
                        new
                        {
                            Id = 148,
                            ISO2 = "MQ",
                            ISO3 = "MTQ",
                            NameEn = " ",
                            NameEs = "Martinica"
                        },
                        new
                        {
                            Id = 149,
                            ISO2 = "MR",
                            ISO3 = "MRT",
                            NameEn = " ",
                            NameEs = "Mauritania"
                        },
                        new
                        {
                            Id = 150,
                            ISO2 = "MS",
                            ISO3 = "MSR",
                            NameEn = " ",
                            NameEs = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            ISO2 = "MT",
                            ISO3 = "MLT",
                            NameEn = " ",
                            NameEs = "Malta"
                        },
                        new
                        {
                            Id = 152,
                            ISO2 = "MU",
                            ISO3 = "MUS",
                            NameEn = " ",
                            NameEs = "Mauricio"
                        },
                        new
                        {
                            Id = 153,
                            ISO2 = "MV",
                            ISO3 = "MDV",
                            NameEn = " ",
                            NameEs = "Maldivas"
                        },
                        new
                        {
                            Id = 154,
                            ISO2 = "MW",
                            ISO3 = "MWI",
                            NameEn = " ",
                            NameEs = "Malawi"
                        },
                        new
                        {
                            Id = 155,
                            ISO2 = "MX",
                            ISO3 = "MEX",
                            NameEn = " ",
                            NameEs = "México"
                        },
                        new
                        {
                            Id = 156,
                            ISO2 = "MY",
                            ISO3 = "MYS",
                            NameEn = " ",
                            NameEs = "Malasia"
                        },
                        new
                        {
                            Id = 157,
                            ISO2 = "MZ",
                            ISO3 = "MOZ",
                            NameEn = " ",
                            NameEs = "Mozambique"
                        },
                        new
                        {
                            Id = 158,
                            ISO2 = "NA",
                            ISO3 = "NAM",
                            NameEn = " ",
                            NameEs = "Namibia"
                        },
                        new
                        {
                            Id = 159,
                            ISO2 = "NC",
                            ISO3 = "NCL",
                            NameEn = " ",
                            NameEs = "Nueva Caledonia"
                        },
                        new
                        {
                            Id = 160,
                            ISO2 = "NE",
                            ISO3 = "NER",
                            NameEn = " ",
                            NameEs = "Níger"
                        },
                        new
                        {
                            Id = 161,
                            ISO2 = "NF",
                            ISO3 = "NFK",
                            NameEn = " ",
                            NameEs = "Isla Norfolk"
                        },
                        new
                        {
                            Id = 162,
                            ISO2 = "NG",
                            ISO3 = "NGA",
                            NameEn = " ",
                            NameEs = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            ISO2 = "NI",
                            ISO3 = "NIC",
                            NameEn = " ",
                            NameEs = "Nicaragua"
                        },
                        new
                        {
                            Id = 164,
                            ISO2 = "NL",
                            ISO3 = "NLD",
                            NameEn = " ",
                            NameEs = "Países Bajos"
                        },
                        new
                        {
                            Id = 165,
                            ISO2 = "NO",
                            ISO3 = "NOR",
                            NameEn = " ",
                            NameEs = "Noruega"
                        },
                        new
                        {
                            Id = 166,
                            ISO2 = "NP",
                            ISO3 = "NPL",
                            NameEn = " ",
                            NameEs = "Nepal"
                        },
                        new
                        {
                            Id = 167,
                            ISO2 = "NR",
                            ISO3 = "NRU",
                            NameEn = " ",
                            NameEs = "Naurú"
                        },
                        new
                        {
                            Id = 168,
                            ISO2 = "NU",
                            ISO3 = "NIU",
                            NameEn = " ",
                            NameEs = "Niue"
                        },
                        new
                        {
                            Id = 169,
                            ISO2 = "NZ",
                            ISO3 = "NZL",
                            NameEn = " ",
                            NameEs = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 170,
                            ISO2 = "OM",
                            ISO3 = "OMN",
                            NameEn = " ",
                            NameEs = "Omán"
                        },
                        new
                        {
                            Id = 171,
                            ISO2 = "PA",
                            ISO3 = "PAN",
                            NameEn = " ",
                            NameEs = "Panamá"
                        },
                        new
                        {
                            Id = 172,
                            ISO2 = "PE",
                            ISO3 = "PER",
                            NameEn = " ",
                            NameEs = "Perú"
                        },
                        new
                        {
                            Id = 173,
                            ISO2 = "PF",
                            ISO3 = "PYF",
                            NameEn = " ",
                            NameEs = "Polinesia Francesa"
                        },
                        new
                        {
                            Id = 174,
                            ISO2 = "PG",
                            ISO3 = "PNG",
                            NameEn = " ",
                            NameEs = "Papúa-Nueva Guinea"
                        },
                        new
                        {
                            Id = 175,
                            ISO2 = "PH",
                            ISO3 = "PHL",
                            NameEn = " ",
                            NameEs = "Filipinas"
                        },
                        new
                        {
                            Id = 176,
                            ISO2 = "PK",
                            ISO3 = "PAK",
                            NameEn = " ",
                            NameEs = "Pakistán"
                        },
                        new
                        {
                            Id = 177,
                            ISO2 = "PL",
                            ISO3 = "POL",
                            NameEn = " ",
                            NameEs = "Polonia"
                        },
                        new
                        {
                            Id = 178,
                            ISO2 = "PM",
                            ISO3 = "SPM",
                            NameEn = " ",
                            NameEs = "San Pedro y Miquelón"
                        },
                        new
                        {
                            Id = 179,
                            ISO2 = "PN",
                            ISO3 = "PCN",
                            NameEn = " ",
                            NameEs = "Pitcairn"
                        },
                        new
                        {
                            Id = 180,
                            ISO2 = "PR",
                            ISO3 = "PRI",
                            NameEn = " ",
                            NameEs = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            ISO2 = "PS",
                            ISO3 = "PSE",
                            NameEn = " ",
                            NameEs = "Estado de Palestina"
                        },
                        new
                        {
                            Id = 182,
                            ISO2 = "PT",
                            ISO3 = "PRT",
                            NameEn = " ",
                            NameEs = "Portugal"
                        },
                        new
                        {
                            Id = 183,
                            ISO2 = "PW",
                            ISO3 = "PLW",
                            NameEn = " ",
                            NameEs = "Palau"
                        },
                        new
                        {
                            Id = 184,
                            ISO2 = "PY",
                            ISO3 = "PRY",
                            NameEn = " ",
                            NameEs = "Paraguay"
                        },
                        new
                        {
                            Id = 185,
                            ISO2 = "QA",
                            ISO3 = "QAT",
                            NameEn = " ",
                            NameEs = "Qatar"
                        },
                        new
                        {
                            Id = 186,
                            ISO2 = "RE",
                            ISO3 = "REU",
                            NameEn = " ",
                            NameEs = "Reunión"
                        },
                        new
                        {
                            Id = 187,
                            ISO2 = "RO",
                            ISO3 = "ROM",
                            NameEn = " ",
                            NameEs = "Rumania"
                        },
                        new
                        {
                            Id = 188,
                            ISO2 = "RS",
                            ISO3 = "SRB",
                            NameEn = " ",
                            NameEs = "Serbia"
                        },
                        new
                        {
                            Id = 189,
                            ISO2 = "RU",
                            ISO3 = "RUS",
                            NameEn = " ",
                            NameEs = "Rusia"
                        },
                        new
                        {
                            Id = 190,
                            ISO2 = "RW",
                            ISO3 = "RWA",
                            NameEn = " ",
                            NameEs = "Ruanda"
                        },
                        new
                        {
                            Id = 191,
                            ISO2 = "SA",
                            ISO3 = "SAU",
                            NameEn = " ",
                            NameEs = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 192,
                            ISO2 = "SB",
                            ISO3 = "SLB",
                            NameEn = " ",
                            NameEs = "Islas Salomón"
                        },
                        new
                        {
                            Id = 193,
                            ISO2 = "SC",
                            ISO3 = "SYC",
                            NameEn = " ",
                            NameEs = "Seychelles"
                        },
                        new
                        {
                            Id = 194,
                            ISO2 = "SD",
                            ISO3 = "SDN",
                            NameEn = " ",
                            NameEs = "Sudán"
                        },
                        new
                        {
                            Id = 195,
                            ISO2 = "SE",
                            ISO3 = "SWE",
                            NameEn = " ",
                            NameEs = "Suecia"
                        },
                        new
                        {
                            Id = 196,
                            ISO2 = "SG",
                            ISO3 = "SGP",
                            NameEn = " ",
                            NameEs = "Singapur"
                        },
                        new
                        {
                            Id = 197,
                            ISO2 = "SH",
                            ISO3 = "SHN",
                            NameEn = " ",
                            NameEs = "Santa Helena"
                        },
                        new
                        {
                            Id = 198,
                            ISO2 = "SI",
                            ISO3 = "SVN",
                            NameEn = " ",
                            NameEs = "Eslovenia"
                        },
                        new
                        {
                            Id = 199,
                            ISO2 = "SJ",
                            ISO3 = "SJM",
                            NameEn = " ",
                            NameEs = "Svalbard y Jan Mayen"
                        },
                        new
                        {
                            Id = 200,
                            ISO2 = "SK",
                            ISO3 = "SVK",
                            NameEn = " ",
                            NameEs = "Eslovaquia"
                        },
                        new
                        {
                            Id = 201,
                            ISO2 = "SL",
                            ISO3 = "SLE",
                            NameEn = " ",
                            NameEs = "Sierra Leona"
                        },
                        new
                        {
                            Id = 202,
                            ISO2 = "SM",
                            ISO3 = "SMR",
                            NameEn = " ",
                            NameEs = "San Marino"
                        },
                        new
                        {
                            Id = 203,
                            ISO2 = "SN",
                            ISO3 = "SEN",
                            NameEn = " ",
                            NameEs = "Senegal"
                        },
                        new
                        {
                            Id = 204,
                            ISO2 = "SO",
                            ISO3 = "SOM",
                            NameEn = " ",
                            NameEs = "Somalia"
                        },
                        new
                        {
                            Id = 205,
                            ISO2 = "SR",
                            ISO3 = "SUR",
                            NameEn = " ",
                            NameEs = "Surinam"
                        },
                        new
                        {
                            Id = 206,
                            ISO2 = "ST",
                            ISO3 = "STP",
                            NameEn = " ",
                            NameEs = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 207,
                            ISO2 = "SV",
                            ISO3 = "SLV",
                            NameEn = " ",
                            NameEs = "El Salvador"
                        },
                        new
                        {
                            Id = 208,
                            ISO2 = "SY",
                            ISO3 = "SYR",
                            NameEn = " ",
                            NameEs = "Siria"
                        },
                        new
                        {
                            Id = 209,
                            ISO2 = "SZ",
                            ISO3 = "SWZ",
                            NameEn = " ",
                            NameEs = "Swazilandia"
                        },
                        new
                        {
                            Id = 210,
                            ISO2 = "TC",
                            ISO3 = "TCA",
                            NameEn = " ",
                            NameEs = "Isla Turks y Caicos"
                        },
                        new
                        {
                            Id = 211,
                            ISO2 = "TD",
                            ISO3 = "TCD",
                            NameEn = " ",
                            NameEs = "Chad"
                        },
                        new
                        {
                            Id = 212,
                            ISO2 = "TF",
                            ISO3 = "ATF",
                            NameEn = " ",
                            NameEs = "Territorios Franceses del Sur"
                        },
                        new
                        {
                            Id = 213,
                            ISO2 = "TG",
                            ISO3 = "TGO",
                            NameEn = " ",
                            NameEs = "Togo"
                        },
                        new
                        {
                            Id = 214,
                            ISO2 = "TH",
                            ISO3 = "THA",
                            NameEn = " ",
                            NameEs = "Tailandia"
                        },
                        new
                        {
                            Id = 215,
                            ISO2 = "TJ",
                            ISO3 = "TJK",
                            NameEn = " ",
                            NameEs = "Tajikistán"
                        },
                        new
                        {
                            Id = 216,
                            ISO2 = "TK",
                            ISO3 = "TKL",
                            NameEn = " ",
                            NameEs = "Tokelau"
                        },
                        new
                        {
                            Id = 217,
                            ISO2 = "TL",
                            ISO3 = "TKM",
                            NameEn = " ",
                            NameEs = "Timor Este"
                        },
                        new
                        {
                            Id = 218,
                            ISO2 = "TM",
                            ISO3 = "TUN",
                            NameEn = " ",
                            NameEs = "Turkmenistán"
                        },
                        new
                        {
                            Id = 219,
                            ISO2 = "TN",
                            ISO3 = "TON",
                            NameEn = " ",
                            NameEs = "Tunicia"
                        },
                        new
                        {
                            Id = 220,
                            ISO2 = "TO",
                            ISO3 = "TMP",
                            NameEn = " ",
                            NameEs = "Tonga"
                        },
                        new
                        {
                            Id = 221,
                            ISO2 = "TR",
                            ISO3 = "TUR",
                            NameEn = " ",
                            NameEs = "Turquía"
                        },
                        new
                        {
                            Id = 222,
                            ISO2 = "TT",
                            ISO3 = "TTO",
                            NameEn = " ",
                            NameEs = "Trinidad y Toba "
                        },
                        new
                        {
                            Id = 223,
                            ISO2 = "TV",
                            ISO3 = "TUV",
                            NameEn = " ",
                            NameEs = "Tuvalú"
                        },
                        new
                        {
                            Id = 224,
                            ISO2 = "TW",
                            ISO3 = "TWN",
                            NameEn = " ",
                            NameEs = "Taiwán"
                        },
                        new
                        {
                            Id = 225,
                            ISO2 = "TZ",
                            ISO3 = "TZA",
                            NameEn = " ",
                            NameEs = "Tanzania"
                        },
                        new
                        {
                            Id = 226,
                            ISO2 = "UA",
                            ISO3 = "UKR",
                            NameEn = " ",
                            NameEs = "Ucrania"
                        },
                        new
                        {
                            Id = 227,
                            ISO2 = "UG",
                            ISO3 = "UGA",
                            NameEn = " ",
                            NameEs = "Uganda"
                        },
                        new
                        {
                            Id = 228,
                            ISO2 = "UM",
                            ISO3 = "UMI",
                            NameEn = " ",
                            NameEs = "Islas Menores de Estados Unidos"
                        },
                        new
                        {
                            Id = 229,
                            ISO2 = "US",
                            ISO3 = "USA",
                            NameEn = " ",
                            NameEs = "Estados Unidos"
                        },
                        new
                        {
                            Id = 230,
                            ISO2 = "UY",
                            ISO3 = "URY",
                            NameEn = " ",
                            NameEs = "Uruguay"
                        },
                        new
                        {
                            Id = 231,
                            ISO2 = "UZ",
                            ISO3 = "UZB",
                            NameEn = " ",
                            NameEs = "Uzbekistán"
                        },
                        new
                        {
                            Id = 232,
                            ISO2 = "VA",
                            ISO3 = "VAT",
                            NameEn = " ",
                            NameEs = "El Vaticano"
                        },
                        new
                        {
                            Id = 233,
                            ISO2 = "VC",
                            ISO3 = "VCT",
                            NameEn = " ",
                            NameEs = "San Vicente y Granadinas"
                        },
                        new
                        {
                            Id = 234,
                            ISO2 = "VE",
                            ISO3 = "VEN",
                            NameEn = " ",
                            NameEs = "Venezuela"
                        },
                        new
                        {
                            Id = 235,
                            ISO2 = "VG",
                            ISO3 = "VGB",
                            NameEn = " ",
                            NameEs = "Islas Vírgenes Británicas"
                        },
                        new
                        {
                            Id = 236,
                            ISO2 = "VI",
                            ISO3 = "VIR",
                            NameEn = " ",
                            NameEs = "Islas Vírgenes de Estados Unidos"
                        },
                        new
                        {
                            Id = 237,
                            ISO2 = "VN",
                            ISO3 = "VNM",
                            NameEn = " ",
                            NameEs = "Vietnam"
                        },
                        new
                        {
                            Id = 238,
                            ISO2 = "VU",
                            ISO3 = "VUT",
                            NameEn = " ",
                            NameEs = "Vanuatu"
                        },
                        new
                        {
                            Id = 239,
                            ISO2 = "WF",
                            ISO3 = "WLF",
                            NameEn = " ",
                            NameEs = "Wallis y Futuna"
                        },
                        new
                        {
                            Id = 240,
                            ISO2 = "WS",
                            ISO3 = "WSM",
                            NameEn = " ",
                            NameEs = "Samoa"
                        },
                        new
                        {
                            Id = 241,
                            ISO2 = "YE",
                            ISO3 = "YEM",
                            NameEn = " ",
                            NameEs = "Yemén"
                        },
                        new
                        {
                            Id = 242,
                            ISO2 = "YT",
                            ISO3 = "MYT",
                            NameEn = " ",
                            NameEs = "Mayotte"
                        },
                        new
                        {
                            Id = 243,
                            ISO2 = "ZA",
                            ISO3 = "ZAF",
                            NameEn = " ",
                            NameEs = "Suráfrica"
                        },
                        new
                        {
                            Id = 244,
                            ISO2 = "ZM",
                            ISO3 = "ZMB",
                            NameEn = " ",
                            NameEs = "Zambia"
                        },
                        new
                        {
                            Id = 245,
                            ISO2 = "ZW",
                            ISO3 = "ZWE",
                            NameEn = " ",
                            NameEs = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("JoinInYear")
                        .HasColumnType("int");

                    b.Property<int>("LeftYear")
                        .HasColumnType("int");

                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("MusicianId");

                    b.ToTable("GroupMember");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ImageType")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(4000)");

                    b.HasKey("Id");

                    b.ToTable("Musician");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.Property<int>("TrackNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GenreId")
                        .IsUnique();

                    b.ToTable("Song");
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Album", b =>
                {
                    b.HasOne("SoundBeats.Core.Domain.Artist", "Artist")
                        .WithMany("Album")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Artist", b =>
                {
                    b.HasOne("SoundBeats.Core.Domain.Country", "Country")
                        .WithOne("Artist")
                        .HasForeignKey("SoundBeats.Core.Domain.Artist", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.GroupMember", b =>
                {
                    b.HasOne("SoundBeats.Core.Domain.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundBeats.Core.Domain.Musician", "Musician")
                        .WithMany("GroupMember")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoundBeats.Core.Domain.Song", b =>
                {
                    b.HasOne("SoundBeats.Core.Domain.Album", "Album")
                        .WithMany("Song")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoundBeats.Core.Domain.Genre", "Genre")
                        .WithOne("Song")
                        .HasForeignKey("SoundBeats.Core.Domain.Song", "GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
